'use server';
/**
 * @fileOverview This file implements a Genkit flow for processing user queries
 * and attached files, sending them to an AI agent network, and returning a
 * context-aware response. It acts as the core interaction point for the
 * AgentConnect Console.
 *
 * - receiveAgentNetworkResponses - The main function to interact with the AI agent network.
 * - ReceiveAgentNetworkResponsesInput - The input type for the receiveAgentNetworkResponses function.
 * - ReceiveAgentNetworkResponsesOutput - The return type for the receiveAgentNetworkResponses function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ReceiveAgentNetworkResponsesInputSchema = z.object({
  query: z.string().describe('The user\'s natural language query for the AI agent network.'),
  files: z
    .array(
      z.object({
        dataUri: z
          .string()
          .describe(
            "A file's content as a data URI, which must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
          ),
        mimeType: z.string().describe('The MIME type of the attached file (e.g., application/pdf, image/jpeg).'),
        fileName: z.string().describe('The original name of the attached file.'),
      })
    )
    .optional()
    .describe('An optional array of files to provide context to the AI agent network.'),
});
export type ReceiveAgentNetworkResponsesInput = z.infer<typeof ReceiveAgentNetworkResponsesInputSchema>;

const ReceiveAgentNetworkResponsesOutputSchema = z.object({
  response: z.string().describe('The intelligent, context-aware response generated by the AI agent network.'),
});
export type ReceiveAgentNetworkResponsesOutput = z.infer<typeof ReceiveAgentNetworkResponsesOutputSchema>;

export async function receiveAgentNetworkResponses(
  input: ReceiveAgentNetworkResponsesInput
): Promise<ReceiveAgentNetworkResponsesOutput> {
  return receiveAgentNetworkResponsesFlow(input);
}

const receiveAgentNetworkResponsesPrompt = ai.definePrompt({
  name: 'receiveAgentNetworkResponsesPrompt',
  input: { schema: ReceiveAgentNetworkResponsesInputSchema },
  output: { schema: ReceiveAgentNetworkResponsesOutputSchema },
  prompt: `You are an intelligent AI agent network designed to provide context-aware responses to user queries.
Analyze the user's query and any provided files to generate a comprehensive and insightful answer.

User Query: {{{query}}}

{{#if files}}
Attached Files:
{{#each files}}
  File ({{this.fileName}}, Type: {{this.mimeType}}): {{media url=this.dataUri}}
{{/each}}
{{/if}}

Based on the query and the content of the attached files, generate a detailed and accurate response.
`,
});

const receiveAgentNetworkResponsesFlow = ai.defineFlow(
  {
    name: 'receiveAgentNetworkResponsesFlow',
    inputSchema: ReceiveAgentNetworkResponsesInputSchema,
    outputSchema: ReceiveAgentNetworkResponsesOutputSchema,
  },
  async (input) => {
    const { output } = await receiveAgentNetworkResponsesPrompt(input);
    if (!output) {
      throw new Error('AI agent network did not provide a response.');
    }
    return output;
  }
);
